default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "postgres://postgres:postgres@localhost:5432/learning_integrations_development") %>

test:
  <<: *default
  url: <%= ENV.fetch("TEST_DATABASE_URL", "postgres://postgres:postgres@localhost:5432/learning_integrations_test") %>

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") %>
